# Generated by Django 5.1 on 2024-08-11 04:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        db_comment="Book title",
                        help_text="Book title",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "author",
                    models.CharField(
                        blank=True,
                        db_comment="Book author",
                        help_text="Book author",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "cover",
                    models.CharField(
                        choices=[("HARD", "Hard"), ("SOFT", "Soft")],
                        db_comment="Book cover",
                        help_text="Book cover",
                        max_length=5,
                    ),
                ),
                (
                    "inventory",
                    models.IntegerField(
                        db_comment="Book inventory",
                        default=0,
                        help_text="Book inventory",
                        validators=[
                            django.core.validators.MinValueValidator(0)
                        ],
                    ),
                ),
                (
                    "daily_fee",
                    models.DecimalField(
                        db_comment="Book daily fee",
                        decimal_places=2,
                        default=0.0,
                        help_text="Book daily fee",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0.0)
                        ],
                    ),
                ),
            ],
            options={
                "ordering": ["title", "author"],
                "indexes": [
                    models.Index(
                        fields=["title", "author"],
                        name="books_book_title_b7b426_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("title", "author"), name="unique_book"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("inventory__gte", 0)),
                        name="inventory_check",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("daily_fee__gte", 0)),
                        name="daily_fee_check",
                    ),
                ],
            },
        ),
    ]
